export interface Quote {
  text: string;
  author: string;
}

/** 100 aphorisms by Greek philosophers; drawn in random order, one per cycle */
export const QUOTES: Quote[] = [
  { text: "Kendini tanı.", author: "Sokrates" },
  { text: "Sorgulanmamış hayat, yaşanmaya değmez.", author: "Sokrates" },
  { text: "Bildiğim tek şey, hiçbir şey bilmediğimdir.", author: "Sokrates" },
  { text: "Adaletsizliğe uğramak, adaletsizlik yapmaktan iyidir.", author: "Sokrates" },
  { text: "İhtiyaç, icadın anasıdır.", author: "Platon" },
  { text: "Sevmek, ölümsüzlüğü aramaktır.", author: "Platon" },
  { text: "Küçük şeylerle mutlu olabilen gerçekten zengindir.", author: "Platon" },
  { text: "Kendini yenen, güçlüdür.", author: "Platon" },
  { text: "Erdem, alışkanlıkla kazanılır.", author: "Aristoteles" },
  { text: "Doğa hiçbir şeyi boşuna yapmaz.", author: "Aristoteles" },
  { text: "Mutluluk, kendine yeterli olmaktır.", author: "Aristoteles" },
  { text: "Arkadaşlık, tek ruhta yaşayan iki bedendir.", author: "Aristoteles" },
  { text: "Aynı ırmağa iki kez giremezsin.", author: "Herakleitos" },
  { text: "Her şey akar, hiçbir şey durmaz.", author: "Herakleitos" },
  { text: "Karakter, kaderdir.", author: "Herakleitos" },
  { text: "Zıtlıkların savaşı, her şeyin babasıdır.", author: "Herakleitos" },
  { text: "Güneş de her gün yenidir.", author: "Herakleitos" },
  { text: "Ölüm, bizim için bir şey ifade etmez.", author: "Epikuros" },
  { text: "İsteklerini azalt, mutluluğu yakala.", author: "Epikuros" },
  { text: "Küçük bir ekmekle bile mutlu yaşanır.", author: "Epikuros" },
  { text: "Dostluk, mutluluğun en büyük kaynağıdır.", author: "Epikuros" },
  { text: "Özgürlük, insanın en değerli malıdır.", author: "Diogenes" },
  { text: "Bir avuç su, koca bir çanağa bedeldir.", author: "Diogenes" },
  { text: "Güneşin aydınlattığı her yerde benim de payım var.", author: "Diogenes" },
  { text: "Kendini yenen, dünyayı yener.", author: "Demokritos" },
  { text: "Mutluluk, ruhta ikamet eder.", author: "Demokritos" },
  { text: "Ölçülülük, hazları artırır.", author: "Demokritos" },
  { text: "Bilgelik, mutluluğun en yüksek biçimidir.", author: "Demokritos" },
  { text: "İnsan her şeyin ölçüsüdür.", author: "Protagoras" },
  { text: "Her şeyin iki yüzü vardır; biri iyi, biri kötü.", author: "Protagoras" },
  { text: "Bizi üzen şeyler olaylar değil, onlara bakışımızdır.", author: "Epiktetos" },
  { text: "Özgürlük, arzularının esiri olmamaktır.", author: "Epiktetos" },
  { text: "İnsanı köle yapan, bedeni değil ruhudur.", author: "Epiktetos" },
  { text: "Her şey sayıdır.", author: "Pythagoras" },
  { text: "Sükuttan iyisini söyleyemeyeceksen, sus.", author: "Pythagoras" },
  { text: "Mutluluk, sağlıklı beden ve huzurlu ruhtur.", author: "Thales" },
  { text: "Her şey, her şeyde gizlidir.", author: "Anaksagoras" },
  { text: "Acı çekerek öğreniriz.", author: "Aiskhylos" },
  { text: "İnsandan daha güçlü hiçbir şey yoktur.", author: "Sophokles" },
  { text: "İkinci düşünce, daha iyi düşüncedir.", author: "Euripides" },
  { text: "Erdem, mutluluk için yeterlidir.", author: "Antisthenes" },
  { text: "Ne düşünürsen, öyle yaşa.", author: "Bias" },
  { text: "Kimseyi ölmeden mutlu sayma.", author: "Solon" },
  { text: "Öfkelenince yavaşla, düşün.", author: "Periandros" },
  { text: "Her şeyde ölçülü ol.", author: "Kleobulos" },
  { text: "Ne yaparsan, düşünerek yap.", author: "Pittakos" },
  { text: "Zaman, her şeyin ilacıdır.", author: "Menandros" },
  { text: "Kendini tanımak, bilgeliğin başlangıcıdır.", author: "Khilon" },
  { text: "Çok konuşma, az dinle.", author: "Khilon" },
  { text: "Mutluluk, erdeme uygun yaşamaktır.", author: "Zenon" },
  { text: "Ne kadar az şeye ihtiyacın varsa, tanrılara o kadar yakınsın.", author: "Sokrates" },
  { text: "Konuş ki seni göreyim.", author: "Sokrates" },
  { text: "Öğrenmek, insanın en soylu uğraşıdır.", author: "Sokrates" },
  { text: "Merak, bilgeliğin kapısıdır.", author: "Sokrates" },
  { text: "Cehalet, tüm kötülüklerin anasıdır.", author: "Platon" },
  { text: "Gözler, ruhun aynasıdır.", author: "Platon" },
  { text: "İyi yaşam, ölçülü yaşamdır.", author: "Platon" },
  { text: "Cesaret, korku ve cüretin doğru ölçüsüdür.", author: "Platon" },
  { text: "İyi başlangıç, işin yarısıdır.", author: "Aristoteles" },
  { text: "Eğitimin kökü acı, meyvesi tatlıdır.", author: "Aristoteles" },
  { text: "İnsan, doğası gereği bilmek ister.", author: "Aristoteles" },
  { text: "Her şeyin ortası en iyisidir.", author: "Aristoteles" },
  { text: "Gözler, kulaklardan daha iyi tanıktır.", author: "Herakleitos" },
  { text: "Doğa gizlenmeyi sever.", author: "Herakleitos" },
  { text: "Uyanık olan, gerçeği görür.", author: "Herakleitos" },
  { text: "Kibir, felaketin habercisidir.", author: "Herakleitos" },
  { text: "Hiçbir haz, kendiliğinden kötü değildir.", author: "Epikuros" },
  { text: "Azla yetinen, en zengindir.", author: "Epikuros" },
  { text: "Doğayla uyum, en büyük öğretmendir.", author: "Epikuros" },
  { text: "Korku, cehaletin kızıdır.", author: "Epikuros" },
  { text: "Sahip oldukların, sana sahip olmasın.", author: "Diogenes" },
  { text: "İhtiyaçların azaldıkça, özgürlüğün artar.", author: "Diogenes" },
  { text: "Krala da köleye de aynı güneş doğar.", author: "Diogenes" },
  { text: "İnsan, doğasına uygun yaşamalıdır.", author: "Diogenes" },
  { text: "Söz, eylemin gölgesidir.", author: "Demokritos" },
  { text: "Cesaret, talihsizlikleri yener.", author: "Demokritos" },
  { text: "Kötü alışkanlık, görünmez zincirdir.", author: "Demokritos" },
  { text: "Mutluluğu kendi içinde ara.", author: "Demokritos" },
  { text: "Önce kendini tanı, sonra dünyayı.", author: "Epiktetos" },
  { text: "Zorluklar, insanın karakterini gösterir.", author: "Epiktetos" },
  { text: "Mutluluk, tepkilerindedir.", author: "Epiktetos" },
  { text: "Başkalarını değil, kendini yargıla.", author: "Epiktetos" },
  { text: "Arkadaşın, kendinin ikinci yarısıdır.", author: "Pythagoras" },
  { text: "Düzen, güzelliğin kardeşidir.", author: "Pythagoras" },
  { text: "Doğruyu söylemek, en kısa yoldur.", author: "Pythagoras" },
  { text: "Umudun varsa, zenginsin.", author: "Thales" },
  { text: "Geleceği düşünen, bugünü planlar.", author: "Thales" },
  { text: "Zihin, her şeyin düzenleyicisidir.", author: "Anaksagoras" },
  { text: "Bilgelik, deneyimle gelir.", author: "Aiskhylos" },
  { text: "Zaman, her şeyi bilen tek tanıktır.", author: "Sophokles" },
  { text: "İnsan aklı, doğanın en büyük armağanıdır.", author: "Sophokles" },
  { text: "Bilge olmak, susmasını bilmektir.", author: "Euripides" },
  { text: "Birlik, güç doğurur.", author: "Euripides" },
  { text: "Bilgelik, en güçlü kaledir.", author: "Antisthenes" },
  { text: "Doğanın yasasına uy, huzuru bul.", author: "Zenon" },
  { text: "Öğrenmek istiyorsan, sor.", author: "Ksenophon" },
  { text: "Güzel söz, güzel düşüncenin meyvesidir.", author: "Isokrates" },
  { text: "Söz, güçlü bir efendidir.", author: "Gorgias" },
  { text: "Akıl, insanın en büyük gücüdür.", author: "Khrysippos" },
  { text: "Yaşamak için öğren, öğrenmek için yaşa.", author: "Sokrates" },
];
