export interface Quote {
  text: string;
  author: string;
}

/** 50 aphorisms by Greek philosophers, one per cycle */
export const QUOTES: Quote[] = [
  { text: "Kendini tanı.", author: "Sokrates" },
  { text: "Sorgulanmamış hayat, yaşanmaya değmez.", author: "Sokrates" },
  { text: "Bildiğim tek şey, hiçbir şey bilmediğimdir.", author: "Sokrates" },
  { text: "Adaletsizliğe uğramak, adaletsizlik yapmaktan iyidir.", author: "Sokrates" },
  { text: "İhtiyaç, icadın anasıdır.", author: "Platon" },
  { text: "Sevmek, ölümsüzlüğü aramaktır.", author: "Platon" },
  { text: "Küçük şeylerle mutlu olabilen gerçekten zengindir.", author: "Platon" },
  { text: "Kendini yenen, güçlüdür.", author: "Platon" },
  { text: "Erdem, alışkanlıkla kazanılır.", author: "Aristoteles" },
  { text: "Doğa hiçbir şeyi boşuna yapmaz.", author: "Aristoteles" },
  { text: "Mutluluk, kendine yeterli olmaktır.", author: "Aristoteles" },
  { text: "Arkadaşlık, tek ruhta yaşayan iki bedendir.", author: "Aristoteles" },
  { text: "Aynı ırmağa iki kez giremezsin.", author: "Herakleitos" },
  { text: "Her şey akar, hiçbir şey durmaz.", author: "Herakleitos" },
  { text: "Karakter, kaderdir.", author: "Herakleitos" },
  { text: "Zıtlıkların savaşı, her şeyin babasıdır.", author: "Herakleitos" },
  { text: "Güneş de her gün yenidir.", author: "Herakleitos" },
  { text: "Ölüm, bizim için bir şey ifade etmez.", author: "Epikuros" },
  { text: "İsteklerini azalt, mutluluğu yakala.", author: "Epikuros" },
  { text: "Küçük bir ekmekle bile mutlu yaşanır.", author: "Epikuros" },
  { text: "Dostluk, mutluluğun en büyük kaynağıdır.", author: "Epikuros" },
  { text: "Özgürlük, insanın en değerli malıdır.", author: "Diogenes" },
  { text: "Bir avuç su, koca bir çanağa bedeldir.", author: "Diogenes" },
  { text: "Güneşin aydınlattığı her yerde benim de payım var.", author: "Diogenes" },
  { text: "Kendini yenen, dünyayı yener.", author: "Demokritos" },
  { text: "Mutluluk, ruhta ikamet eder.", author: "Demokritos" },
  { text: "Ölçülülük, hazları artırır.", author: "Demokritos" },
  { text: "Bilgelik, mutluluğun en yüksek biçimidir.", author: "Demokritos" },
  { text: "İnsan her şeyin ölçüsüdür.", author: "Protagoras" },
  { text: "Her şeyin iki yüzü vardır; biri iyi, biri kötü.", author: "Protagoras" },
  { text: "Bizi üzen şeyler olaylar değil, onlara bakışımızdır.", author: "Epiktetos" },
  { text: "Özgürlük, arzularının esiri olmamaktır.", author: "Epiktetos" },
  { text: "İnsanı köle yapan, bedeni değil ruhudur.", author: "Epiktetos" },
  { text: "Her şey sayıdır.", author: "Pythagoras" },
  { text: "Sükuttan iyisini söyleyemeyeceksen, sus.", author: "Pythagoras" },
  { text: "Mutluluk, sağlıklı beden ve huzurlu ruhtur.", author: "Thales" },
  { text: "Her şey, her şeyde gizlidir.", author: "Anaksagoras" },
  { text: "Acı çekerek öğreniriz.", author: "Aiskhylos" },
  { text: "İnsandan daha güçlü hiçbir şey yoktur.", author: "Sophokles" },
  { text: "İkinci düşünce, daha iyi düşüncedir.", author: "Euripides" },
  { text: "Erdem, mutluluk için yeterlidir.", author: "Antisthenes" },
  { text: "Ne düşünürsen, öyle yaşa.", author: "Bias" },
  { text: "Kimseyi ölmeden mutlu sayma.", author: "Solon" },
  { text: "Öfkelenince yavaşla, düşün.", author: "Periandros" },
  { text: "Her şeyde ölçülü ol.", author: "Kleobulos" },
  { text: "Ne yaparsan, düşünerek yap.", author: "Pittakos" },
  { text: "Zaman, her şeyin ilacıdır.", author: "Menandros" },
  { text: "Kendini tanımak, bilgeliğin başlangıcıdır.", author: "Khilon" },
  { text: "Çok konuşma, az dinle.", author: "Khilon" },
  { text: "Mutluluk, erdeme uygun yaşamaktır.", author: "Zenon" },
];
