export type LangCode = "tr" | "en" | "zh" | "hi" | "es" | "fr" | "ar" | "bn" | "pt";

export interface Quote {
  text: string;
  author: string;
}

/** canonical author key for every quote (index-aligned with QUOTE_TEXTS) */
const AUTHORS: string[] = [
  "Sokrates", "Sokrates", "Sokrates", "Sokrates",
  "Platon", "Platon", "Platon", "Platon",
  "Aristoteles", "Aristoteles", "Aristoteles", "Aristoteles",
  "Herakleitos", "Herakleitos", "Herakleitos", "Herakleitos", "Herakleitos",
  "Epikuros", "Epikuros", "Epikuros", "Epikuros",
  "Diogenes", "Diogenes", "Diogenes", "Diogenes",
  "Demokritos", "Demokritos", "Demokritos", "Demokritos",
  "Protagoras", "Protagoras",
  "Epiktetos", "Epiktetos", "Epiktetos",
  "Pythagoras", "Pythagoras",
  "Thales",
  "Anaksagoras",
  "Aiskhylos",
  "Sophokles",
  "Euripides",
  "Antisthenes",
  "Bias",
  "Solon",
  "Periandros",
  "Kleobulos",
  "Pittakos",
  "Menandros",
  "Khilon", "Khilon",
  "Zenon",
  "Sokrates", "Sokrates", "Sokrates", "Sokrates",
  "Platon", "Platon", "Platon", "Platon",
  "Aristoteles", "Aristoteles", "Aristoteles", "Aristoteles",
  "Herakleitos", "Herakleitos", "Herakleitos", "Herakleitos",
  "Epikuros", "Epikuros", "Epikuros", "Epikuros",
  "Diogenes", "Diogenes", "Diogenes", "Diogenes",
  "Demokritos", "Demokritos", "Demokritos", "Demokritos",
  "Epiktetos", "Epiktetos", "Epiktetos", "Epiktetos",
  "Pythagoras", "Pythagoras", "Pythagoras",
  "Thales", "Thales",
  "Anaksagoras",
  "Aiskhylos",
  "Sophokles", "Sophokles",
  "Euripides", "Euripides",
  "Antisthenes",
  "Zenon",
  "Ksenophon",
  "Isokrates",
  "Gorgias",
  "Khrysippos",
  "Sokrates",
];

/** 100 aphorisms by Greek philosophers, one per cycle, per language */
export const QUOTE_TEXTS: Record<LangCode, string[]> = {
  tr: [
    "Kendini tanı.",
    "Sorgulanmamış hayat, yaşanmaya değmez.",
    "Bildiğim tek şey, hiçbir şey bilmediğimdir.",
    "Adaletsizliğe uğramak, adaletsizlik yapmaktan iyidir.",
    "İhtiyaç, icadın anasıdır.",
    "Sevmek, ölümsüzlüğü aramaktır.",
    "Küçük şeylerle mutlu olabilen gerçekten zengindir.",
    "Kendini yenen, güçlüdür.",
    "Erdem, alışkanlıkla kazanılır.",
    "Doğa hiçbir şeyi boşuna yapmaz.",
    "Mutluluk, kendine yeterli olmaktır.",
    "Arkadaşlık, tek ruhta yaşayan iki bedendir.",
    "Aynı ırmağa iki kez giremezsin.",
    "Her şey akar, hiçbir şey durmaz.",
    "Karakter, kaderdir.",
    "Zıtlıkların savaşı, her şeyin babasıdır.",
    "Güneş de her gün yenidir.",
    "Ölüm, bizim için bir şey ifade etmez.",
    "İsteklerini azalt, mutluluğu yakala.",
    "Küçük bir ekmekle bile mutlu yaşanır.",
    "Dostluk, mutluluğun en büyük kaynağıdır.",
    "Özgürlük, insanın en değerli malıdır.",
    "Bir avuç su, koca bir çanağa bedeldir.",
    "Güneşin aydınlattığı her yerde benim de payım var.",
    "Kendini yenen, dünyayı yener.",
    "Mutluluk, ruhta ikamet eder.",
    "Ölçülülük, hazları artırır.",
    "Bilgelik, mutluluğun en yüksek biçimidir.",
    "İnsan her şeyin ölçüsüdür.",
    "Her şeyin iki yüzü vardır; biri iyi, biri kötü.",
    "Bizi üzen şeyler olaylar değil, onlara bakışımızdır.",
    "Özgürlük, arzularının esiri olmamaktır.",
    "İnsanı köle yapan, bedeni değil ruhudur.",
    "Her şey sayıdır.",
    "Sükuttan iyisini söyleyemeyeceksen, sus.",
    "Mutluluk, sağlıklı beden ve huzurlu ruhtur.",
    "Her şey, her şeyde gizlidir.",
    "Acı çekerek öğreniriz.",
    "İnsandan daha güçlü hiçbir şey yoktur.",
    "İkinci düşünce, daha iyi düşüncedir.",
    "Erdem, mutluluk için yeterlidir.",
    "Ne düşünürsen, öyle yaşa.",
    "Kimseyi ölmeden mutlu sayma.",
    "Öfkelenince yavaşla, düşün.",
    "Her şeyde ölçülü ol.",
    "Ne yaparsan, düşünerek yap.",
    "Zaman, her şeyin ilacıdır.",
    "Kendini tanımak, bilgeliğin başlangıcıdır.",
    "Çok konuşma, az dinle.",
    "Mutluluk, erdeme uygun yaşamaktır.",
    "Ne kadar az şeye ihtiyacın varsa, tanrılara o kadar yakınsın.",
    "Konuş ki seni göreyim.",
    "Öğrenmek, insanın en soylu uğraşıdır.",
    "Merak, bilgeliğin kapısıdır.",
    "Cehalet, tüm kötülüklerin anasıdır.",
    "Gözler, ruhun aynasıdır.",
    "İyi yaşam, ölçülü yaşamdır.",
    "Cesaret, korku ve cüretin doğru ölçüsüdür.",
    "İyi başlangıç, işin yarısıdır.",
    "Eğitimin kökü acı, meyvesi tatlıdır.",
    "İnsan, doğası gereği bilmek ister.",
    "Her şeyin ortası en iyisidir.",
    "Gözler, kulaklardan daha iyi tanıktır.",
    "Doğa gizlenmeyi sever.",
    "Uyanık olan, gerçeği görür.",
    "Kibir, felaketin habercisidir.",
    "Hiçbir haz, kendiliğinden kötü değildir.",
    "Azla yetinen, en zengindir.",
    "Doğayla uyum, en büyük öğretmendir.",
    "Korku, cehaletin kızıdır.",
    "Sahip oldukların, sana sahip olmasın.",
    "İhtiyaçların azaldıkça, özgürlüğün artar.",
    "Krala da köleye de aynı güneş doğar.",
    "İnsan, doğasına uygun yaşamalıdır.",
    "Söz, eylemin gölgesidir.",
    "Cesaret, talihsizlikleri yener.",
    "Kötü alışkanlık, görünmez zincirdir.",
    "Mutluluğu kendi içinde ara.",
    "Önce kendini tanı, sonra dünyayı.",
    "Zorluklar, insanın karakterini gösterir.",
    "Mutluluk, tepkilerindedir.",
    "Başkalarını değil, kendini yargıla.",
    "Arkadaşın, kendinin ikinci yarısıdır.",
    "Düzen, güzelliğin kardeşidir.",
    "Doğruyu söylemek, en kısa yoldur.",
    "Umudun varsa, zenginsin.",
    "Geleceği düşünen, bugünü planlar.",
    "Zihin, her şeyin düzenleyicisidir.",
    "Bilgelik, deneyimle gelir.",
    "Zaman, her şeyi bilen tek tanıktır.",
    "İnsan aklı, doğanın en büyük armağanıdır.",
    "Bilge olmak, susmasını bilmektir.",
    "Birlik, güç doğurur.",
    "Bilgelik, en güçlü kaledir.",
    "Doğanın yasasına uy, huzuru bul.",
    "Öğrenmek istiyorsan, sor.",
    "Güzel söz, güzel düşüncenin meyvesidir.",
    "Söz, güçlü bir efendidir.",
    "Akıl, insanın en büyük gücüdür.",
    "Yaşamak için öğren, öğrenmek için yaşa.",
  ],
  en: [
    "Know thyself.",
    "The unexamined life is not worth living.",
    "All I know is that I know nothing.",
    "It is better to suffer injustice than to commit it.",
    "Necessity is the mother of invention.",
    "To love is to seek immortality.",
    "He who can be happy with little is truly rich.",
    "He who conquers himself is strong.",
    "Virtue is acquired through habit.",
    "Nature does nothing in vain.",
    "Happiness is being self-sufficient.",
    "Friendship is two bodies living in one soul.",
    "You cannot step into the same river twice.",
    "Everything flows, nothing stands still.",
    "Character is destiny.",
    "The strife of opposites is the father of all things.",
    "The sun is new each day.",
    "Death is nothing to us.",
    "Lessen your desires and grasp happiness.",
    "One can live happily with a small piece of bread.",
    "Friendship is the greatest source of happiness.",
    "Freedom is a person's most precious possession.",
    "A handful of water is worth a great bowl.",
    "Wherever the sun shines, I have a share.",
    "He who conquers himself conquers the world.",
    "Happiness dwells in the soul.",
    "Moderation increases pleasures.",
    "Wisdom is the highest form of happiness.",
    "Man is the measure of all things.",
    "Every thing has two sides; one good, one bad.",
    "It is not events but our view of them that troubles us.",
    "Freedom is not being a slave to your desires.",
    "It is not the body but the soul that makes one a slave.",
    "All is number.",
    "If you cannot say anything better than silence, be silent.",
    "Happiness is a healthy body and a peaceful soul.",
    "Everything is hidden in everything.",
    "We learn by suffering.",
    "Nothing is more powerful than man.",
    "The second thought is the better thought.",
    "Virtue is sufficient for happiness.",
    "Live as you think.",
    "Count no man happy until he is dead.",
    "When angered, slow down and think.",
    "Be moderate in all things.",
    "Whatever you do, do it with thought.",
    "Time is the remedy for all things.",
    "To know oneself is the beginning of wisdom.",
    "Speak little, listen much.",
    "Happiness is living in accordance with virtue.",
    "The fewer your needs, the closer you are to the gods.",
    "Speak, so that I may see you.",
    "Learning is humanity's noblest pursuit.",
    "Curiosity is the gateway to wisdom.",
    "Ignorance is the mother of all evil.",
    "The eyes are the mirror of the soul.",
    "The good life is a measured life.",
    "Courage is the right measure between fear and audacity.",
    "A good beginning is half the work.",
    "The root of education is bitter, its fruit is sweet.",
    "By nature, man desires to know.",
    "The middle of everything is best.",
    "The eyes are better witnesses than the ears.",
    "Nature loves to hide.",
    "The one who is awake sees the truth.",
    "Arrogance is the herald of disaster.",
    "No pleasure is bad in itself.",
    "He who is content with little is the richest.",
    "Harmony with nature is the greatest teacher.",
    "Fear is the daughter of ignorance.",
    "Let not your possessions possess you.",
    "The fewer your needs, the greater your freedom.",
    "The same sun rises for the king and the slave.",
    "Man should live in accordance with his nature.",
    "The word is the shadow of the deed.",
    "Courage overcomes misfortunes.",
    "A bad habit is an invisible chain.",
    "Seek happiness within yourself.",
    "First know yourself, then the world.",
    "Difficulties reveal a person's character.",
    "Happiness lies in your reactions.",
    "Judge not others, but yourself.",
    "Your friend is your other half.",
    "Order is the sister of beauty.",
    "Telling the truth is the shortest path.",
    "If you have hope, you are rich.",
    "He who thinks of the future plans for today.",
    "The mind is the ordering principle of all things.",
    "Wisdom comes with experience.",
    "Time is the only witness that knows everything.",
    "The human mind is nature's greatest gift.",
    "To be wise is to know when to keep silent.",
    "Unity breeds strength.",
    "Wisdom is the strongest fortress.",
    "Follow the law of nature and find peace.",
    "If you wish to learn, ask.",
    "A beautiful word is the fruit of a beautiful thought.",
    "Speech is a powerful master.",
    "Reason is a person's greatest power.",
    "Learn in order to live, live in order to learn.",
  ],
  zh: [
    "认识你自己。",
    "未经省察的人生不值得过。",
    "我只知道一件事，那就是我一无所知。",
    "遭受不义胜过施行不义。",
    "需要是发明之母。",
    "爱就是追寻不朽。",
    "能以小事物为乐者，才是真正的富有。",
    "战胜自己者，方为强者。",
    "美德由习惯养成。",
    "自然从不做无用之事。",
    "幸福在于自足。",
    "友谊是两个身体共居一个灵魂。",
    "人不能两次踏入同一条河流。",
    "万物皆流，无物常驻。",
    "性格即命运。",
    "对立之争是万物之父。",
    "太阳每天都是新的。",
    "死亡与我们无关。",
    "减少欲望，方能抓住幸福。",
    "哪怕一小块面包也能幸福地生活。",
    "友谊是幸福的最大源泉。",
    "自由是人之最宝贵的财富。",
    "一把水抵得上一个大碗。",
    "太阳照耀之处，亦有我的一份。",
    "战胜自己者，战胜世界。",
    "幸福寓居于灵魂之中。",
    "节制增进快乐。",
    "智慧是幸福的最高形式。",
    "人是万物的尺度。",
    "万物皆有两面；一善一恶。",
    "困扰我们的不是事情本身，而是我们对事情的看法。",
    "自由就是不做欲望的奴隶。",
    "使人成为奴隶的不是身体，而是灵魂。",
    "万物皆数。",
    "若无胜于沉默之语，宁可沉默。",
    "幸福就是健康的身体和平静的灵魂。",
    "万物都潜藏于万物之中。",
    "我们通过苦难学习。",
    "没有什么比人更强大。",
    "第二次思考才是更好的思考。",
    "美德足以带来幸福。",
    "所思即所行。",
    "人之未死，勿言其福。",
    "发怒时，放慢脚步，想一想。",
    "凡事适度。",
    "无论做什么，都要三思而行。",
    "时间是一切的良药。",
    "认识自己是智慧的开端。",
    "少说，多听。",
    "幸福就是遵循美德而生活。",
    "需要越少，离神越近。",
    "说句话吧，好让我看见你。",
    "学习是人类最高尚的事业。",
    "好奇是智慧之门。",
    "无知是万恶之源。",
    "眼睛是灵魂的镜子。",
    "好的生活是节制的生活。",
    "勇敢是恐惧与鲁莽之间的正确尺度。",
    "好的开始是成功的一半。",
    "教育的根是苦的，果实是甜的。",
    "人天生渴望求知。",
    "凡事中庸最佳。",
    "眼睛比耳朵更可靠。",
    "自然喜爱隐藏自己。",
    "清醒者看见真理。",
    "傲慢是灾难的先兆。",
    "没有一种快乐本身是坏的。",
    "知足者最富有。",
    "与自然和谐是最伟大的老师。",
    "恐惧是无知之女。",
    "别让身外之物占据你的心。",
    "需求越少，自由越大。",
    "国王与奴隶头顶同一个太阳。",
    "人应当顺应自己的本性生活。",
    "言语是行动的影子。",
    "勇气战胜厄运。",
    "坏习惯是看不见的锁链。",
    "在自身之内寻找幸福。",
    "先认识自己，再认识世界。",
    "困难显露出人的品格。",
    "幸福在于你的反应。",
    "不要评判他人，要评判自己。",
    "朋友是你的另一半。",
    "秩序是美的姊妹。",
    "说真话是最短的路。",
    "有希望者即富有。",
    "思虑未来者，筹划今日。",
    "心灵是万物的安排者。",
    "智慧来自经验。",
    "时间是无所不知的唯一见证者。",
    "人的智慧是自然最大的馈赠。",
    "有智慧就是懂得沉默。",
    "团结生力量。",
    "智慧是最坚固的堡垒。",
    "顺应自然的法则，便得安宁。",
    "想学习，就要发问。",
    "美言是美思之果。",
    "言语是一位强大的主宰。",
    "理性是人最强大的力量。",
    "为生活而学习，为学习而生活。",
  ],
  hi: [
    "स्वयं को जानो।",
    "अनदेखी की गई ज़िंदगी जीने लायक नहीं है।",
    "मैं केवल इतना जानता हूँ कि मैं कुछ नहीं जानता।",
    "अन्याय सहना, अन्याय करने से बेहतर है।",
    "आवश्यकता आविष्कार की जननी है।",
    "प्रेम करना अमरता की खोज है।",
    "जो थोड़े से खुश रह सकता है, वही सचमुच धनी है।",
    "जो स्वयं को जीत लेता है, वही शक्तिशाली है।",
    "सद्गुण आदत से अर्जित होता है।",
    "प्रकृति कुछ भी व्यर्थ नहीं करती।",
    "खुशी आत्मनिर्भर होने में है।",
    "मित्रता एक आत्मा में रहने वाले दो शरीर हैं।",
    "एक ही नदी में दो बार उतरना असंभव है।",
    "सब कुछ बहता है, कुछ भी स्थिर नहीं।",
    "चरित्र ही भाग्य है।",
    "विरोधों का संघर्ष सभी चीज़ों का पिता है।",
    "सूरज भी हर दिन नया है।",
    "मृत्यु हमारे लिए कुछ भी नहीं है।",
    "इच्छाएँ कम करो, सुख पकड़ो।",
    "एक छोटी सी रोटी से भी सुखपूर्वक जिया जा सकता है।",
    "मित्रता सुख का सबसे बड़ा स्रोत है।",
    "स्वतंत्रता मनुष्य की सबसे मूल्यवान संपत्ति है।",
    "एक मुट्ठी पानी एक बड़े कटोरे के बराबर है।",
    "सूर्य जहाँ चमकता है, वहाँ मेरा भी हिस्सा है।",
    "जो स्वयं को जीतता है, वह संसार को जीतता है।",
    "सुख आत्मा में निवास करता है।",
    "संयम आनंद बढ़ाता है।",
    "ज्ञान सुख का सर्वोच्च रूप है।",
    "मनुष्य सभी चीज़ों का माप है।",
    "हर चीज़ के दो पहलू होते हैं; एक अच्छा, एक बुरा।",
    "हमें दुख देने वाली चीज़ें घटनाएँ नहीं, बल्कि उनके प्रति हमारा दृष्टिकोण हैं।",
    "स्वतंत्रता का अर्थ है अपनी इच्छाओं का गुलाम न होना।",
    "मनुष्य को दास बनाता है शरीर नहीं, आत्मा।",
    "सब कुछ संख्या है।",
    "मौन से अच्छा कुछ न कह सको, तो मौन रहो।",
    "सुख स्वस्थ शरीर और शांत आत्मा है।",
    "सब कुछ सब कुछ में छिपा है।",
    "हम कष्ट सहकर सीखते हैं।",
    "मनुष्य से अधिक शक्तिशाली कुछ भी नहीं।",
    "दूसरा विचार बेहतर विचार है।",
    "सुख के लिए सद्गुण ही पर्याप्त है।",
    "जैसा सोचते हो, वैसे ही जियो।",
    "मृत्यु से पहले किसी को सुखी न मानो।",
    "क्रोध आए तो धीमे पड़ो और सोचो।",
    "हर चीज़ में संयम रखो।",
    "जो भी करो, सोच-समझकर करो।",
    "समय सब चीज़ों की दवा है।",
    "स्वयं को जानना ज्ञान की शुरुआत है।",
    "कम बोलो, ज़्यादा सुनो।",
    "सुख सद्गुण के अनुसार जीना है।",
    "जितनी कम ज़रूरतें होंगी, उतने ही देवताओं के करीब होगे।",
    "बोलो, ताकि मैं तुम्हें देख सकूँ।",
    "सीखना मनुष्य का सबसे उत्तम कार्य है।",
    "जिज्ञासा ज्ञान का द्वार है।",
    "अज्ञान सभी बुराइयों की जननी है।",
    "आँखें आत्मा का दर्पण हैं।",
    "अच्छा जीवन संयमित जीवन है।",
    "साहस भय और धृष्टता के बीच का सही माप है।",
    "अच्छी शुरुआत आधा काम है।",
    "शिक्षा की जड़ कड़वी है, फल मीठा।",
    "मनुष्य स्वभाव से जानना चाहता है।",
    "हर चीज़ का मध्य सबसे अच्छा है।",
    "आँखें कानों से बेहतर गवाह हैं।",
    "प्रकृति छिपना पसंद करती है।",
    "जो जाग्रत है, वही सत्य देखता है।",
    "अहंकार आपदा का अग्रदूत है।",
    "कोई भी आनंद स्वयं में बुरा नहीं है।",
    "जो थोड़े से संतुष्ट है, वही सबसे धनी है।",
    "प्रकृति के साथ सामंजस्य सबसे बड़ा गुरु है।",
    "भय अज्ञान की पुत्री है।",
    "तुम्हारी संपत्ति तुम्हारी मालिक न बने।",
    "ज़रूरतें जितनी कम, स्वतंत्रता उतनी अधिक।",
    "राजा और दास के लिए एक ही सूरज उगता है।",
    "मनुष्य को अपने स्वभाव के अनुसार जीना चाहिए।",
    "शब्द कर्म की छाया है।",
    "साहस विपत्तियों को जीतता है।",
    "बुरी आदत एक अदृश्य जंजीर है।",
    "सुख को अपने भीतर खोजो।",
    "पहले स्वयं को जानो, फिर संसार को।",
    "कठिनाइयाँ व्यक्ति का चरित्र दिखाती हैं।",
    "सुख तुम्हारी प्रतिक्रियाओं में है।",
    "दूसरों को नहीं, स्वयं को आँकें।",
    "तुम्हारा मित्र तुम्हारा दूसरा आधा है।",
    "व्यवस्था सौंदर्य की बहन है।",
    "सत्य बोलना सबसे छोटा मार्ग है।",
    "आशा हो तो तुम धनी हो।",
    "जो भविष्य सोचता है, वह आज की योजना बनाता है।",
    "मन ही सब कुछ का व्यवस्थापक है।",
    "ज्ञान अनुभव से आता है।",
    "समय ही एकमात्र गवाह है जो सब कुछ जानता है।",
    "मानव मन प्रकृति का सबसे बड़ा उपहार है।",
    "बुद्धिमान होना मौन रहना जानना है।",
    "एकता शक्ति जन्म देती है।",
    "ज्ञान सबसे मजबूत किला है।",
    "प्रकृति के नियम का पालन करो और शांति पाओ।",
    "सीखना चाहते हो, तो पूछो।",
    "सुंदर वचन सुंदर विचार का फल है।",
    "वाणी एक शक्तिशाली स्वामी है।",
    "बुद्धि मनुष्य की सबसे बड़ी शक्ति है।",
    "जीने के लिए सीखो, सीखने के लिए जियो।",
  ],
  es: [
    "Conócete a ti mismo.",
    "La vida no examinada no merece ser vivida.",
    "Lo único que sé es que no sé nada.",
    "Sufrir injusticia es mejor que cometerla.",
    "La necesidad es la madre de la invención.",
    "Amar es buscar la inmortalidad.",
    "Quien puede ser feliz con poco es realmente rico.",
    "Quien se vence a sí mismo es fuerte.",
    "La virtud se adquiere con el hábito.",
    "La naturaleza no hace nada en vano.",
    "La felicidad es bastarse a uno mismo.",
    "La amistad son dos cuerpos que habitan un solo espíritu.",
    "No puedes bañarte dos veces en el mismo río.",
    "Todo fluye, nada permanece.",
    "El carácter es el destino.",
    "La guerra de los opuestos es el padre de todas las cosas.",
    "El sol también es nuevo cada día.",
    "La muerte no es nada para nosotros.",
    "Reduce tus deseos y alcanza la felicidad.",
    "Se puede vivir feliz incluso con un pequeño pedazo de pan.",
    "La amistad es la mayor fuente de felicidad.",
    "La libertad es el bien más preciado del hombre.",
    "Un puñado de agua vale más que un gran cuenco.",
    "En todo lugar donde brilla el sol, yo tengo mi parte.",
    "Quien se vence a sí mismo vence al mundo.",
    "La felicidad habita en el alma.",
    "La moderación acrecienta los placeres.",
    "La sabiduría es la forma más alta de felicidad.",
    "El hombre es la medida de todas las cosas.",
    "Todo tiene dos caras; una buena y una mala.",
    "No son los acontecimientos sino nuestra forma de verlos lo que nos aflige.",
    "La libertad es no ser esclavo de tus deseos.",
    "Lo que esclaviza al hombre no es el cuerpo sino el alma.",
    "Todo es número.",
    "Si no puedes decir algo mejor que el silencio, calla.",
    "La felicidad es un cuerpo sano y un alma en paz.",
    "Todo está oculto en todo.",
    "Aprendemos sufriendo.",
    "No hay nada más poderoso que el hombre.",
    "El segundo pensamiento es el mejor.",
    "La virtud es suficiente para la felicidad.",
    "Vive como piensas.",
    "No consideres feliz a nadie antes de su muerte.",
    "Cuando te enfades, detente y piensa.",
    "Sé moderado en todo.",
    "Hagas lo que hagas, hazlo pensando.",
    "El tiempo es la medicina de todo.",
    "Conocerse a uno mismo es el comienzo de la sabiduría.",
    "Habla poco, escucha mucho.",
    "La felicidad es vivir conforme a la virtud.",
    "Cuanto menos necesitas, más cerca estás de los dioses.",
    "Habla para que pueda verte.",
    "Aprender es la ocupación más noble del hombre.",
    "La curiosidad es la puerta de la sabiduría.",
    "La ignorancia es la madre de todos los males.",
    "Los ojos son el espejo del alma.",
    "La buena vida es una vida moderada.",
    "El valor es la justa medida entre el miedo y la audacia.",
    "Un buen comienzo es la mitad de la obra.",
    "La raíz de la educación es amarga, pero su fruto es dulce.",
    "El hombre desea saber por naturaleza.",
    "El término medio es lo mejor en todo.",
    "Los ojos son mejores testigos que los oídos.",
    "A la naturaleza le gusta ocultarse.",
    "El que está despierto ve la verdad.",
    "La soberbia es la anunciadora de la desgracia.",
    "Ningún placer es malo por sí mismo.",
    "Quien se conforma con poco es el más rico.",
    "La armonía con la naturaleza es el mayor maestro.",
    "El miedo es hija de la ignorancia.",
    "No dejes que tus posesiones te posean a ti.",
    "Cuantas menos necesidades, más libertad.",
    "El mismo sol sale para el rey y para el esclavo.",
    "El hombre debe vivir conforme a su naturaleza.",
    "La palabra es la sombra de la acción.",
    "El valor vence las desgracias.",
    "El mal hábito es una cadena invisible.",
    "Busca la felicidad dentro de ti.",
    "Conócete a ti mismo primero, luego al mundo.",
    "Las dificultades revelan el carácter del hombre.",
    "La felicidad está en tus reacciones.",
    "No juzgues a los demás, júzgate a ti mismo.",
    "Tu amigo es tu otra mitad.",
    "El orden es hermano de la belleza.",
    "Decir la verdad es el camino más corto.",
    "Si tienes esperanza, eres rico.",
    "Quien piensa en el futuro planifica el presente.",
    "La mente es la ordenadora de todas las cosas.",
    "La sabiduría llega con la experiencia.",
    "El tiempo es el único testigo que lo sabe todo.",
    "La mente humana es el mayor regalo de la naturaleza.",
    "Ser sabio es saber callar.",
    "La unión engendra fuerza.",
    "La sabiduría es la fortaleza más fuerte.",
    "Sigue la ley de la naturaleza y hallarás la paz.",
    "Si quieres aprender, pregunta.",
    "La bella palabra es fruto del bello pensamiento.",
    "La palabra es un poderoso amo.",
    "La razón es el mayor poder del hombre.",
    "Aprende para vivir, vive para aprender.",
  ],
  fr: [
    "Connais-toi toi-même.",
    "Une vie sans examen ne vaut pas la peine d'être vécue.",
    "Tout ce que je sais, c'est que je ne sais rien.",
    "Subir l'injustice vaut mieux que la commettre.",
    "Le besoin est mère de l'invention.",
    "Aimer, c'est chercher l'immortalité.",
    "Qui sait se contenter de peu est vraiment riche.",
    "Celui qui se vainc soi-même est fort.",
    "La vertu s'acquiert par l'habitude.",
    "La nature ne fait rien en vain.",
    "Le bonheur, c'est se suffire à soi-même.",
    "L'amitié est deux corps vivant dans une seule âme.",
    "On ne peut pas entrer deux fois dans le même fleuve.",
    "Tout coule, rien ne demeure.",
    "Le caractère est le destin.",
    "Le conflit des contraires est le père de toutes choses.",
    "Le soleil aussi est nouveau chaque jour.",
    "La mort n'est rien pour nous.",
    "Réduis tes désirs et saisis le bonheur.",
    "On peut vivre heureux même avec un petit morceau de pain.",
    "L'amitié est la plus grande source de bonheur.",
    "La liberté est le bien le plus précieux de l'homme.",
    "Une poignée d'eau vaut un grand bol.",
    "Partout où brille le soleil, j'ai ma part.",
    "Qui se vainc lui-même vainc le monde.",
    "Le bonheur habite dans l'âme.",
    "La modération accroît les plaisirs.",
    "La sagesse est la plus haute forme de bonheur.",
    "L'homme est la mesure de toutes choses.",
    "Toute chose a deux faces; l'une bonne, l'une mauvaise.",
    "Ce qui nous trouble, ce ne sont pas les événements mais notre regard sur eux.",
    "La liberté, c'est ne pas être l'esclave de ses désirs.",
    "Ce qui fait de l'homme un esclave, ce n'est pas le corps mais l'âme.",
    "Tout est nombre.",
    "Si tu ne peux rien dire de mieux que le silence, tais-toi.",
    "Le bonheur, c'est un corps sain et une âme paisible.",
    "Tout est caché dans tout.",
    "C'est en souffrant qu'on apprend.",
    "Rien n'est plus puissant que l'homme.",
    "La seconde pensée est la meilleure.",
    "La vertu suffit au bonheur.",
    "Vis comme tu penses.",
    "Ne dis personne heureux avant sa mort.",
    "Quand tu te fâches, ralentis et réfléchis.",
    "Sois mesuré en toute chose.",
    "Quoi que tu fasses, fais-le en réfléchissant.",
    "Le temps est le remède de toute chose.",
    "Se connaître soi-même est le commencement de la sagesse.",
    "Parle peu, écoute beaucoup.",
    "Le bonheur, c'est vivre selon la vertu.",
    "Moins tu as de besoins, plus tu es proche des dieux.",
    "Parle, afin que je te voie.",
    "Apprendre est la plus noble occupation de l'homme.",
    "La curiosité est la porte de la sagesse.",
    "L'ignorance est la mère de tous les maux.",
    "Les yeux sont le miroir de l'âme.",
    "La bonne vie est une vie mesurée.",
    "Le courage est la juste mesure entre la peur et l'audace.",
    "Un bon début est la moitié de l'ouvrage.",
    "La racine de l'éducation est amère, mais son fruit est doux.",
    "L'homme désire savoir par nature.",
    "Le juste milieu est le meilleur en toute chose.",
    "Les yeux sont de meilleurs témoins que les oreilles.",
    "La nature aime à se cacher.",
    "Celui qui est éveillé voit la vérité.",
    "L'arrogance est l'annonciatrice du désastre.",
    "Aucun plaisir n'est mauvais en soi.",
    "Qui se contente de peu est le plus riche.",
    "L'harmonie avec la nature est le plus grand maître.",
    "La peur est la fille de l'ignorance.",
    "Que tes biens ne te possèdent pas.",
    "Moins tu as de besoins, plus ta liberté est grande.",
    "Le même soleil se lève pour le roi et pour l'esclave.",
    "L'homme doit vivre selon sa nature.",
    "La parole est l'ombre de l'action.",
    "Le courage vainc les malheurs.",
    "Une mauvaise habitude est une chaîne invisible.",
    "Cherche le bonheur en toi-même.",
    "Connais d'abord toi-même, puis le monde.",
    "Les difficultés révèlent le caractère de l'homme.",
    "Le bonheur est dans tes réactions.",
    "Ne juge pas les autres, juge-toi toi-même.",
    "Ton ami est ta seconde moitié.",
    "L'ordre est le frère de la beauté.",
    "Dire la vérité est le chemin le plus court.",
    "Si tu as de l'espoir, tu es riche.",
    "Qui pense à l'avenir prépare le présent.",
    "L'esprit est le principe qui ordonne toutes choses.",
    "La sagesse vient avec l'expérience.",
    "Le temps est l'unique témoin qui sait tout.",
    "L'esprit humain est le plus grand don de la nature.",
    "Être sage, c'est savoir se taire.",
    "L'union engendre la force.",
    "La sagesse est la plus solide des forteresses.",
    "Suis la loi de la nature et tu trouveras la paix.",
    "Si tu veux apprendre, demande.",
    "La belle parole est le fruit de la belle pensée.",
    "La parole est un puissant maître.",
    "La raison est la plus grande force de l'homme.",
    "Apprends pour vivre, vis pour apprendre.",
  ],
  ar: [
    "اعرف نفسك.",
    "الحياة التي لا تُفحص لا تستحق أن تُعاش.",
    "كل ما أعرفه أنني لا أعرف شيئًا.",
    "تحمّل الظلم خير من ارتكابه.",
    "الحاجة أم الاختراع.",
    "الحب هو البحث عن الخلود.",
    "من يستطيع السعادة بالقليل فهو الغني حقًا.",
    "من ينتصر على نفسه فهو قوي.",
    "الفضيلة تُكتسب بالعادة.",
    "الطبيعة لا تفعل شيئًا بلا فائدة.",
    "السعادة هي الاكتفاء بالذات.",
    "الصداقة جسدان يسكنان روحًا واحدة.",
    "لا يمكنك النزول إلى النهر نفسه مرتين.",
    "كل شيء يجري ولا شيء يثبت.",
    "الطبع هو القدر.",
    "صراع الأضداد هو أبو كل الأشياء.",
    "الشمس أيضًا جديدة كل يوم.",
    "الموت لا يعني لنا شيئًا.",
    "قلّل رغباتك لتظفر بالسعادة.",
    "يمكن أن تعيش سعيدًا حتى بقطعة خبز صغيرة.",
    "الصداقة أعظم مصدر للسعادة.",
    "الحرية أغلى ممتلكات الإنسان.",
    "حفنة من الماء تعدل كأسًا عظيمًا.",
    "حيثما أشرقت الشمس فلي نصيب.",
    "من ينتصر على نفسه ينتصر على العالم.",
    "السعادة تسكن في الروح.",
    "الاعتدال يزيد اللذات.",
    "الحكمة أسمى صور السعادة.",
    "الإنسان مقياس كل الأشياء.",
    "لكل شيء وجهان؛ أحدهما خير والآخر شر.",
    "ما يُحزننا ليست الأحداث بل نظرتنا إليها.",
    "الحرية هي ألا تكون عبدًا لرغباتك.",
    "الذي يجعل الإنسان عبدًا ليس الجسد بل الروح.",
    "كل شيء هو عدد.",
    "إن لم تستطع قول ما هو أفضل من الصمت، فاصمت.",
    "السعادة هي جسد صحي وروح هادئة.",
    "كل شيء مختبئ في كل شيء.",
    "نتعلم من خلال المعاناة.",
    "لا شيء أقوى من الإنسان.",
    "الفكرة الثانية هي الأفضل.",
    "الفضيلة تكفي للسعادة.",
    "عِش كما تفكّر.",
    "لا تعتبر أحدًا سعيدًا قبل موته.",
    "عند الغضب تأنَّ وفكّر.",
    "كن معتدلًا في كل شيء.",
    "مهما فعلت فافعله بتفكير.",
    "الزمن دواء كل شيء.",
    "معرفة النفس هي بداية الحكمة.",
    "تكلّم قليلًا واستمع كثيرًا.",
    "السعادة هي العيش وفق الفضيلة.",
    "كلما قلّت حاجاتك اقتربت من الآلهة.",
    "تكلّم حتى أراك.",
    "التعلم أنبل ما يشتغل به الإنسان.",
    "الفضول بوابة الحكمة.",
    "الجهل أم كل الشرور.",
    "العيون مرآة الروح.",
    "الحياة الطيبة هي الحياة المعتدلة.",
    "الشجاعة هي القياس الصحيح بين الخوف والجرأة.",
    "البداية الجيدة نصف العمل.",
    "جذر التعليم مرّ وثمرته حلوة.",
    "الإنسان يرغب بطبيعته في المعرفة.",
    "الوسط هو الأفضل في كل شيء.",
    "العيون شهود أفضل من الآذان.",
    "الطبيعة تحب أن تختبئ.",
    "المستيقظ يرى الحقيقة.",
    "الغرور نذير الكارثة.",
    "لا لذة شريرة بذاتها.",
    "القانع بالقليل هو الأغنى.",
    "الانسجام مع الطبيعة أعظم معلم.",
    "الخوف ابنة الجهل.",
    "لا تدع ما تملك يملكك.",
    "كلما قلّت حاجاتك زادت حريتك.",
    "تشرق الشمس نفسها على الملك والعبد.",
    "على الإنسان أن يعيش وفق طبيعته.",
    "الكلمة ظل الفعل.",
    "الشجاعة تهزم المصائب.",
    "العادة السيئة سلسلة غير مرئية.",
    "ابحث عن السعادة داخل نفسك.",
    "اعرف نفسك أولًا ثم العالم.",
    "الصعوبات تُظهر معدن الإنسان.",
    "السعادة في ردود أفعالك.",
    "لا تحكم على الآخرين بل على نفسك.",
    "صديقك هو نصفك الآخر.",
    "النظام شقيق الجمال.",
    "قول الحقيقة أقصر طريق.",
    "إن كان لديك أمل فأنت غني.",
    "من يفكر في المستقبل يخطط للحاضر.",
    "العقل هو منظم كل الأشياء.",
    "الحكمة تأتي بالتجربة.",
    "الزمن هو الشاهد الوحيد الذي يعرف كل شيء.",
    "العقل البشري أعظم هبة من الطبيعة.",
    "الحكيم من يعرف متى يصمت.",
    "الاتحاد يولد القوة.",
    "الحكمة أقوى حصن.",
    "اتبع قانون الطبيعة تجد السلام.",
    "إن أردت أن تتعلم فاسأل.",
    "الكلمة الجميلة ثمرة الفكرة الجميلة.",
    "الكلمة سيد قوي.",
    "العقل أقوى قوى الإنسان.",
    "تعلّم لتعيش، وعش لتتعلّم.",
  ],
  bn: [
    "নিজেকে জান।",
    "অযাচাই করা জীবন বেঁচে থাকার যোগ্য নয়।",
    "আমি শুধু জানি যে আমি কিছুই জানি না।",
    "অন্যায় সহ্য করা অন্যায় করার চেয়ে ভালো।",
    "প্রয়োজনই আবিষ্কারের জননী।",
    "ভালোবাসা মানে অমরত্বের সন্ধান।",
    "যে অল্পতেই সুখী হতে পারে, সে-ই প্রকৃত ধনী।",
    "যে নিজেকে জয় করে, সে-ই শক্তিশালী।",
    "সৎগুণ অভ্যাসের মাধ্যমে অর্জিত হয়।",
    "প্রকৃতি কিছুই বৃথা করে না।",
    "সুখ হলো আত্মনির্ভর হওয়া।",
    "বন্ধুত্ব হলো এক আত্মায় বসবাসকারী দুই দেহ।",
    "একই নদীতে দুইবার নামা যায় না।",
    "সবকিছু প্রবাহিত হয়, কিছুই স্থির থাকে না।",
    "চরিত্রই ভাগ্য।",
    "বিরোধী শক্তির সংঘাতই সকল কিছুর জনক।",
    "সূর্যেও প্রতিদিন নতুন।",
    "মৃত্যু আমাদের কাছে কিছুই নয়।",
    "ইচ্ছা কমাও, সুখকে আঁকড়ে ধরো।",
    "এক টুকরো রুটিতেও সুখে থাকা যায়।",
    "বন্ধুত্বই সুখের সর্বশ্রেষ্ঠ উৎস।",
    "স্বাধীনতা মানুষের সবচেয়ে মূল্যবান সম্পদ।",
    "এক মুঠো পানি একটি বড় পাত্রের সমান।",
    "যেখানেই সূর্য আলো দেয়, সেখানেই আমার অংশ আছে।",
    "যে নিজেকে জয় করে, সে বিশ্বকে জয় করে।",
    "সুখ আত্মাতেই বাস করে।",
    "সংযম আনন্দ বাড়ায়।",
    "জ্ঞানই সুখের সর্বোচ্চ রূপ।",
    "মানুষই সব কিছুর পরিমাপ।",
    "প্রতিটি জিনিসের দুই দিক আছে; এক ভালো, এক খারাপ।",
    "যা আমাদের কষ্ট দেয় তা ঘটনা নয়, ঘটনাগুলোর প্রতি আমাদের দৃষ্টিভঙ্গি।",
    "স্বাধীনতা মানে নিজের ইচ্ছার দাস না হওয়া।",
    "মানুষকে দাস বানায় দেহ নয়, আত্মা।",
    "সবকিছুই সংখ্যা।",
    "নীরবতার চেয়ে ভালো কিছু বলতে না পারলে চুপ থাকো।",
    "সুখ হলো সুস্থ দেহ ও শান্ত আত্মা।",
    "সবকিছু সবকিছুর মধ্যে লুকিয়ে আছে।",
    "কষ্ট পেয়েই আমরা শিখি।",
    "মানুষের চেয়ে শক্তিশালী কিছুই নেই।",
    "দ্বিতীয় চিন্তাই ভালো চিন্তা।",
    "সুখের জন্য সৎগুণই যথেষ্ট।",
    "যেমন ভাবো, তেমনই বাঁচো।",
    "মৃত্যুর আগে কাউকে সুখী মনে করো না।",
    "রাগ এলে ধীর হও এবং ভাবো।",
    "সবকিছুতেই সংযমী হও।",
    "যা করো, ভেবে করো।",
    "সময়ই সবকিছুর ওষুধ।",
    "নিজেকে জানাই জ্ঞানের সূচনা।",
    "কম কথা বলো, বেশি শোনো।",
    "সুখ হলো সৎগুণ অনুযায়ী জীবনযাপন।",
    "যত কম প্রয়োজনে চলবে, ততই দেবতাদের কাছাকাছি।",
    "বলো, যাতে আমি তোমাকে দেখতে পাই।",
    "শেখা মানুষের সবচেয়ে মহৎ কাজ।",
    "কৌতূহলই জ্ঞানের দরজা।",
    "অজ্ঞতা সকল অকল্যাণের জননী।",
    "চোখ আত্মার দর্পণ।",
    "ভালো জীবন হলো সংযত জীবন।",
    "সাহস হলো ভয় ও সাহসিকতার সঠিক মাত্রা।",
    "ভালো শুরুই কাজের অর্ধেক।",
    "শিক্ষার শিকড় তিক্ত, ফল মিষ্টি।",
    "মানুষ প্রকৃতিগতভাবে জানতে চায়।",
    "সবকিছুর মধ্যপথই সর্বোত্তম।",
    "চোখ কানের চেয়ে ভালো সাক্ষী।",
    "প্রকৃতি লুকিয়ে থাকতে ভালোবাসে।",
    "যে জাগ্রত, সে-ই সত্য দেখে।",
    "অহংকার বিপর্যয়ের অগ্রদূত।",
    "কোনো আনন্দই স্বভাবতই খারাপ নয়।",
    "যে অল্পতেই তুষ্ট, সে-ই সবচেয়ে ধনী।",
    "প্রকৃতির সঙ্গে সামঞ্জস্যই শ্রেষ্ঠ শিক্ষক।",
    "ভয় অজ্ঞতার কন্যা।",
    "তোমার সম্পত্তি যেন তোমাকে অধিকার না করে।",
    "প্রয়োজন যত কম, স্বাধীনতা তত বেশি।",
    "রাজা আর দাসের জন্যও একই সূর্য ওঠে।",
    "মানুষের নিজ প্রকৃতি অনুযায়ী বাঁচা উচিত।",
    "বাক্য কর্মের ছায়া।",
    "সাহস দুর্ভাগ্যকে জয় করে।",
    "খারাপ অভ্যাস একটি অদৃশ্য শিকল।",
    "সুখকে নিজের ভিতরে খোঁজো।",
    "আগে নিজেকে জানো, তারপর দুনিয়াকে।",
    "কষ্ট মানুষের চরিত্র প্রকাশ করে।",
    "সুখ তোমার প্রতিক্রিয়াতেই।",
    "অন্যের নয়, নিজেকেই বিচার করো।",
    "তোমার বন্ধুই তোমার অন্য অর্ধেক।",
    "শৃঙ্খলা সৌন্দর্যের ভগিনী।",
    "সত্য বলা সবচেয়ে সংক্ষিপ্ত পথ।",
    "আশা থাকলে তুমিই ধনী।",
    "যে ভবিষ্যৎ ভাবে, সে আজকের পরিকল্পনা করে।",
    "মনই সবকিছুর নিয়ন্ত্রক।",
    "জ্ঞান অভিজ্ঞতার সঙ্গে আসে।",
    "সময়ই একমাত্র সাক্ষী যে সব জানে।",
    "মানব মন প্রকৃতির সবচেয়ে বড় উপহার।",
    "বিজ্ঞ হওয়া মানে নীরব থাকতে জানা।",
    "ঐক্যই শক্তির জন্ম দেয়।",
    "জ্ঞানই সবচেয়ে শক্তিশালী দুর্গ।",
    "প্রকৃতির নিয়ম মেনে চলো, শান্তি পাবে।",
    "শিখতে চাইলে জিজ্ঞেস করো।",
    "সুন্দর কথা সুন্দর চিন্তার ফল।",
    "বাক্য এক শক্তিশালী প্রভু।",
    "বুদ্ধি মানুষের সবচেয়ে বড় শক্তি।",
    "বাঁচতে শেখো, শিখতে বাঁচো।",
  ],
  pt: [
    "Conhece-te a ti mesmo.",
    "A vida não examinada não vale a pena ser vivida.",
    "Só sei que nada sei.",
    "Sofrer injustiça é melhor do que cometê-la.",
    "A necessidade é a mãe da invenção.",
    "Amar é buscar a imortalidade.",
    "Quem consegue ser feliz com pouco é verdadeiramente rico.",
    "Quem vence a si mesmo é forte.",
    "A virtude se adquire com o hábito.",
    "A natureza nada faz em vão.",
    "A felicidade é bastar-se a si mesmo.",
    "A amizade são dois corpos que habitam uma só alma.",
    "Não se pode entrar duas vezes no mesmo rio.",
    "Tudo flui, nada permanece.",
    "O caráter é o destino.",
    "O conflito dos opostos é o pai de todas as coisas.",
    "O sol também é novo a cada dia.",
    "A morte nada é para nós.",
    "Reduza seus desejos e alcance a felicidade.",
    "É possível viver feliz até com um pequeno pedaço de pão.",
    "A amizade é a maior fonte de felicidade.",
    "A liberdade é o bem mais precioso do homem.",
    "Um punhado de água vale um grande recipiente.",
    "Em todo lugar onde o sol brilha, tenho minha parte.",
    "Quem vence a si mesmo vence o mundo.",
    "A felicidade habita na alma.",
    "A moderação aumenta os prazeres.",
    "A sabedoria é a forma mais elevada de felicidade.",
    "O homem é a medida de todas as coisas.",
    "Toda coisa tem dois lados; um bom, um mau.",
    "Não são os acontecimentos, mas a nossa forma de vê-los que nos perturba.",
    "Liberdade é não ser escravo dos seus desejos.",
    "O que escraviza o homem não é o corpo, mas a alma.",
    "Tudo é número.",
    "Se não podes dizer algo melhor que o silêncio, cala-te.",
    "A felicidade é um corpo saudável e uma alma serena.",
    "Tudo está escondido em tudo.",
    "Aprendemos sofrendo.",
    "Não há nada mais poderoso que o homem.",
    "O segundo pensamento é o melhor.",
    "A virtude é suficiente para a felicidade.",
    "Vive como pensas.",
    "Não consideres ninguém feliz antes da morte.",
    "Ao te enfurecer, acalma-te e pensa.",
    "Sê moderado em tudo.",
    "Faças o que fizeres, faze-o com pensamento.",
    "O tempo é o remédio de todas as coisas.",
    "Conhecer-se a si mesmo é o começo da sabedoria.",
    "Fala pouco, ouve muito.",
    "A felicidade é viver de acordo com a virtude.",
    "Quanto menos precisas, mais perto estás dos deuses.",
    "Fala, para que eu te veja.",
    "Aprender é a ocupação mais nobre do homem.",
    "A curiosidade é a porta da sabedoria.",
    "A ignorância é a mãe de todos os males.",
    "Os olhos são o espelho da alma.",
    "A boa vida é uma vida moderada.",
    "A coragem é a justa medida entre o medo e a audácia.",
    "Um bom começo é metade da obra.",
    "A raiz da educação é amarga, mas o seu fruto é doce.",
    "O homem deseja saber por natureza.",
    "O meio-termo é o melhor em tudo.",
    "Os olhos são melhores testemunhas que os ouvidos.",
    "A natureza gosta de se esconder.",
    "Quem está desperto vê a verdade.",
    "A arrogância é o prenúncio do desastre.",
    "Nenhum prazer é mau em si mesmo.",
    "Quem se contenta com pouco é o mais rico.",
    "A harmonia com a natureza é o maior mestre.",
    "O medo é filho da ignorância.",
    "Não deixes que os teus bens te possuam.",
    "Quanto menos necessidades, maior a liberdade.",
    "O mesmo sol nasce para o rei e para o escravo.",
    "O homem deve viver de acordo com a sua natureza.",
    "A palavra é a sombra da ação.",
    "A coragem vence as desgraças.",
    "Um mau hábito é uma corrente invisível.",
    "Procura a felicidade dentro de ti.",
    "Conhece-te primeiro a ti mesmo, depois o mundo.",
    "As dificuldades revelam o caráter do homem.",
    "A felicidade está nas tuas reações.",
    "Não julgues os outros, julga-te a ti mesmo.",
    "O teu amigo é a tua outra metade.",
    "A ordem é irmã da beleza.",
    "Dizer a verdade é o caminho mais curto.",
    "Se tens esperança, és rico.",
    "Quem pensa no futuro planeia o presente.",
    "A mente é a ordenadora de todas as coisas.",
    "A sabedoria vem com a experiência.",
    "O tempo é a única testemunha que sabe tudo.",
    "A mente humana é o maior dom da natureza.",
    "Ser sábio é saber calar-se.",
    "A união gera força.",
    "A sabedoria é a fortaleza mais forte.",
    "Segue a lei da natureza e encontrarás a paz.",
    "Se queres aprender, pergunta.",
    "A bela palavra é fruto do belo pensamento.",
    "A palavra é um poderoso senhor.",
    "A razão é o maior poder do homem.",
    "Aprende para viver, vive para aprender.",
  ],
};

/** localized author names, keyed by canonical (Turkish) name */
const AUTHOR_NAMES: Record<LangCode, Record<string, string>> = {
  tr: {
    Sokrates: "Sokrates", Platon: "Platon", Aristoteles: "Aristoteles",
    Herakleitos: "Herakleitos", Epikuros: "Epikuros", Diogenes: "Diogenes",
    Demokritos: "Demokritos", Protagoras: "Protagoras", Epiktetos: "Epiktetos",
    Pythagoras: "Pythagoras", Thales: "Thales", Anaksagoras: "Anaksagoras",
    Aiskhylos: "Aiskhylos", Sophokles: "Sophokles", Euripides: "Euripides",
    Antisthenes: "Antisthenes", Bias: "Bias", Solon: "Solon",
    Periandros: "Periandros", Kleobulos: "Kleobulos", Pittakos: "Pittakos",
    Menandros: "Menandros", Khilon: "Khilon", Zenon: "Zenon",
    Ksenophon: "Ksenophon", Isokrates: "Isokrates", Gorgias: "Gorgias",
    Khrysippos: "Khrysippos",
  },
  en: {
    Sokrates: "Socrates", Platon: "Plato", Aristoteles: "Aristotle",
    Herakleitos: "Heraclitus", Epikuros: "Epicurus", Diogenes: "Diogenes",
    Demokritos: "Democritus", Protagoras: "Protagoras", Epiktetos: "Epictetus",
    Pythagoras: "Pythagoras", Thales: "Thales", Anaksagoras: "Anaxagoras",
    Aiskhylos: "Aeschylus", Sophokles: "Sophocles", Euripides: "Euripides",
    Antisthenes: "Antisthenes", Bias: "Bias", Solon: "Solon",
    Periandros: "Periander", Kleobulos: "Cleobulus", Pittakos: "Pittacus",
    Menandros: "Menander", Khilon: "Chilon", Zenon: "Zeno",
    Ksenophon: "Xenophon", Isokrates: "Isocrates", Gorgias: "Gorgias",
    Khrysippos: "Chrysippus",
  },
  zh: {
    Sokrates: "苏格拉底", Platon: "柏拉图", Aristoteles: "亚里士多德",
    Herakleitos: "赫拉克利特", Epikuros: "伊壁鸠鲁", Diogenes: "第欧根尼",
    Demokritos: "德谟克利特", Protagoras: "普罗泰戈拉", Epiktetos: "爱比克泰德",
    Pythagoras: "毕达哥拉斯", Thales: "泰勒斯", Anaksagoras: "阿那克萨戈拉",
    Aiskhylos: "埃斯库罗斯", Sophokles: "索福克勒斯", Euripides: "欧里庇得斯",
    Antisthenes: "安提西尼", Bias: "彼亚斯", Solon: "梭伦",
    Periandros: "佩里安德", Kleobulos: "克莱俄布卢", Pittakos: "庇塔库斯",
    Menandros: "米南德", Khilon: "喀隆", Zenon: "芝诺",
    Ksenophon: "色诺芬", Isokrates: "伊索克拉底", Gorgias: "高尔吉亚",
    Khrysippos: "克律西波斯",
  },
  hi: {
    Sokrates: "सुकरात", Platon: "प्लेटो", Aristoteles: "अरस्तू",
    Herakleitos: "हेराक्लीटस", Epikuros: "एपिकुरस", Diogenes: "डायोजनीज",
    Demokritos: "डेमोक्रिटस", Protagoras: "प्रोटागोरस", Epiktetos: "एपिक्टेटस",
    Pythagoras: "पाइथागोरस", Thales: "थेल्स", Anaksagoras: "एनाक्सागोरस",
    Aiskhylos: "एशिलस", Sophokles: "सोफोकल्स", Euripides: "यूरिपिडीज",
    Antisthenes: "एंटिस्थनीज", Bias: "बायस", Solon: "सोलन",
    Periandros: "पेरियांड्रोस", Kleobulos: "क्लियोबुलस", Pittakos: "पिट्टाकोस",
    Menandros: "मेनान्द्रोस", Khilon: "चिलोन", Zenon: "ज़ेनो",
    Ksenophon: "ज़ेनोफोन", Isokrates: "इसोक्रेटस", Gorgias: "गोर्गियास",
    Khrysippos: "क्रिसिप्पोस",
  },
  es: {
    Sokrates: "Sócrates", Platon: "Platón", Aristoteles: "Aristóteles",
    Herakleitos: "Heráclito", Epikuros: "Epicuro", Diogenes: "Diógenes",
    Demokritos: "Demócrito", Protagoras: "Protágoras", Epiktetos: "Epicteto",
    Pythagoras: "Pitágoras", Thales: "Tales", Anaksagoras: "Anaxágoras",
    Aiskhylos: "Esquilo", Sophokles: "Sófocles", Euripides: "Eurípides",
    Antisthenes: "Antístenes", Bias: "Bías", Solon: "Solón",
    Periandros: "Periandro", Kleobulos: "Cleóbulo", Pittakos: "Pítaco",
    Menandros: "Menandro", Khilon: "Quilón", Zenon: "Zenón",
    Ksenophon: "Jenofonte", Isokrates: "Isócrates", Gorgias: "Gorgias",
    Khrysippos: "Crisipo",
  },
  fr: {
    Sokrates: "Socrate", Platon: "Platon", Aristoteles: "Aristote",
    Herakleitos: "Héraclite", Epikuros: "Épicure", Diogenes: "Diogène",
    Demokritos: "Démocrite", Protagoras: "Protagoras", Epiktetos: "Épictète",
    Pythagoras: "Pythagore", Thales: "Thalès", Anaksagoras: "Anaxagore",
    Aiskhylos: "Eschyle", Sophokles: "Sophocle", Euripides: "Euripide",
    Antisthenes: "Antisthène", Bias: "Bias", Solon: "Solon",
    Periandros: "Périandre", Kleobulos: "Cléobule", Pittakos: "Pittacos",
    Menandros: "Ménandre", Khilon: "Chilon", Zenon: "Zénon",
    Ksenophon: "Xénophon", Isokrates: "Isocrate", Gorgias: "Gorgias",
    Khrysippos: "Chrysippe",
  },
  ar: {
    Sokrates: "سقراط", Platon: "أفلاطون", Aristoteles: "أرسطو",
    Herakleitos: "هيراقليطس", Epikuros: "أبيقور", Diogenes: "ديوجين",
    Demokritos: "ديموقريطس", Protagoras: "بروتاغوراس", Epiktetos: "إبكتيتوس",
    Pythagoras: "فيثاغورس", Thales: "طاليس", Anaksagoras: "أناكساغورس",
    Aiskhylos: "إسخيلوس", Sophokles: "سوفوكليس", Euripides: "يوربيديس",
    Antisthenes: "أنتيسثينيس", Bias: "بياس", Solon: "سولون",
    Periandros: "برياندر", Kleobulos: "كليوبولوس", Pittakos: "بيتاكوس",
    Menandros: "ميناندر", Khilon: "خيلون", Zenon: "زينون",
    Ksenophon: "زينوفون", Isokrates: "إيسقراط", Gorgias: "غورغياس",
    Khrysippos: "كريسيبوس",
  },
  bn: {
    Sokrates: "সক্রেটিস", Platon: "প্লেটো", Aristoteles: "এরিস্টটল",
    Herakleitos: "হেরাক্লিটাস", Epikuros: "এপিকুরাস", Diogenes: "ডায়োজেনিস",
    Demokritos: "ডেমোক্রিটাস", Protagoras: "প্রোটাগোরাস", Epiktetos: "এপিকটেটাস",
    Pythagoras: "পিথাগোরাস", Thales: "থ্যালেস", Anaksagoras: "আনাক্সাগোরাস",
    Aiskhylos: "এসকাইলাস", Sophokles: "সোফোক্লেস", Euripides: "ইউরিপিডিস",
    Antisthenes: "অ্যান্টিসথেনেস", Bias: "বায়াস", Solon: "সোলন",
    Periandros: "পেরিয়ান্ডার", Kleobulos: "ক্লিওবুলাস", Pittakos: "পিটাকাস",
    Menandros: "মেনান্ডার", Khilon: "চিলন", Zenon: "জেনো",
    Ksenophon: "জেনোফোন", Isokrates: "আইসোক্রেটিস", Gorgias: "গর্গিয়াস",
    Khrysippos: "ক্রিসিপ্পাস",
  },
  pt: {
    Sokrates: "Sócrates", Platon: "Platão", Aristoteles: "Aristóteles",
    Herakleitos: "Heráclito", Epikuros: "Epicuro", Diogenes: "Diógenes",
    Demokritos: "Demócrito", Protagoras: "Protágoras", Epiktetos: "Epicteto",
    Pythagoras: "Pitágoras", Thales: "Tales", Anaksagoras: "Anaxágoras",
    Aiskhylos: "Ésquilo", Sophokles: "Sófocles", Euripides: "Eurípides",
    Antisthenes: "Antístenes", Bias: "Bias", Solon: "Sólon",
    Periandros: "Periandro", Kleobulos: "Cleóbulo", Pittakos: "Pítaco",
    Menandros: "Menandro", Khilon: "Quílon", Zenon: "Zenão",
    Ksenophon: "Xenofonte", Isokrates: "Isócrates", Gorgias: "Górgias",
    Khrysippos: "Crisipo",
  },
};

/** aphorism list for the given language, authors localized */
export function quotesFor(lang: LangCode): Quote[] {
  const texts = QUOTE_TEXTS[lang];
  const names = AUTHOR_NAMES[lang];
  return texts.map((text, i) => ({
    text,
    author: names[AUTHORS[i]!] ?? AUTHORS[i]!,
  }));
}
